#INCLUDE "TOTVS.CH"
#INCLUDE "TLPP-REST.TH"
#INCLUDE "TLPP-CORE.TH"

namespace customdummyauth

/*/{Protheus.doc} className
    Service, class criada para iniciar e passar os campos do Json para buscar o usuario e a senha da API e receber 
    o retorno
    @author Arthur Loni
    @since 28/05/2026
/*/

Class ServiceAuthUser

    Public Data oData     as Object
    Public Data jResponse as jResponse

    Public Method New()              as Variant 
    Public Method BuscaUser()        as Variant
    Public Method MontaJsonRetorno() as Variant    

EndClass

Method New() Class ServiceAuthUser

    self:oData     := NIL
    self:jResponse := NIL

Return

Method BuscaUser(cParams as Character) Class ServiceAuthUser

    self:oData := BuscaUser():New()
    self:oData:BuscaUser(cParams)

Return

Method MontaJsonRetorno() Class ServiceAuthUser

    self:jResponse := JsonObject():New()

    self:jResponse['username'] := self:oData:Username()
    self:jResponse['password'] := self:oData:Password()

Return ::jResponse
