#INCLUDE "TOTVS.CH"
#INCLUDE "TLPP-CORE.TH"
#INCLUDE "TLPP-REST.TH"

Class ControllerBuscaUser

    Public Data oService    as Object
    Public Data jResponse   as Json
    Public Data jParams     as Json

    Public Method New()

    @GET("/DUMMY/api/v1/BuscaUser")
    Public Method BuscaUser()

EndClass

Method New() Class ControllerBuscaUser
    ::oService := Nil
Return

Method BuscaUser() Class ControllerBuscaUser

    ::jParams := oRest:getQueryRequest()

    ::oService := serviceBuscaUser():New()

    ::jResponse := ::oService:montaJsonRetorno()

	oRest:setResponse(::jResponse:ToJson())
	oRest:setKeyHeaderResponse('Content-Type','application/json')

Return
